Rolo/Models/Playground.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Rolo.Models
{
    public class Playground
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual PlaygroundFeature Features { get; set; }
        public virtual Image Image { get; set; }
		public double Latitude { get; set; }
		public double Longitude { get; set; }
    }
}

Rolo/ViewModels/PlaygroundViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Rolo.Models;
using Rolo.ViewModels;

namespace Rolo.ViewModels
{
	public class PlaygroundViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public PlaygroundFeature Features { get; set; }
		public Image PlaygroundImage { get; set; }
		public double Latitude { get; set; }
		public double Longitude { get; set; }
		public List<PostViewModel> Posts { get; set; }
		public List<UserListViewModel> ActiveFriends { get; set; }
		public bool CurrentUserIsCheckedIn { get; set; }
        public bool CurrentUserIsFollowing { get; set; }
		public int Range { get; set; }
		public double Rating { get; set; }
        public PlaygroundRating CurrentUserRating { get; set; }
	}
}

Rolo/Controllers/PlaygroundController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rolo.Models;
using Rolo.DAL;
using Rolo.Services;
using Rolo.ViewModels;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Rolo.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class PlaygroundController : ExceptionController
    {
        private AdminService aService = new AdminService(null);

        // GET: /Playground/
        public ActionResult Index()
        {
            return View(aService.GetAllPlaygrounds());
        }

        // GET: /Playground/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Playground playground = aService.GetPlaygroundWithId(id.Value);
            if (playground == null)
            {
                return HttpNotFound();
            }
            return View(playground);
        }

        // GET: /Playground/Create
        public ActionResult Create()
        {
            return View(new PlaygroundViewModel());
        }

        // POST: /Playground/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // [Bind(Include = "Id,Name,Latitude,Longitude")]
       // public ActionResult Create(FormCollection collection, HttpPostedFileBase image, PlaygroundFeature feature)
        public ActionResult Create(PlaygroundViewModel model, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                Playground newPlayground = new Playground();
                newPlayground.Name = model.Name;
                newPlayground.Latitude = model.Latitude;
                newPlayground.Longitude = model.Longitude;
                newPlayground.Features = model.Features;

                Image playgroundImage = new Image();
                
                if (image != null && image.ContentLength > 0)
                {
                    string userId = User.Identity.GetUserId();
                    var fileName = Path.GetFileName(image.FileName);
                    var path = AppDomain.CurrentDomain.BaseDirectory + "\\Data\\" + fileName;
                    image.SaveAs(path);
                    newPlayground.Image = new Image { Path = String.Format("/Data/{0}", fileName) };
                }

                aService.AddPlayground(newPlayground);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: /Playground/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Playground playground = aService.GetPlaygroundWithId(id.Value);
            if (playground == null)
            {
                return HttpNotFound();
            }
            return View(playground);
        }

        // POST: /Playground/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Latitude,Longitude")] Playground playground)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                db.Entry(playground).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(playground);
        }

        // GET: /Playground/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Playground playground = aService.GetPlaygroundWithId(id.Value);
            if (playground == null)
            {
                return HttpNotFound();
            }
            return View(playground);
        }

        // POST: /Playground/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            aService.RemovePlaygroundWithId(id);
            return RedirectToAction("Index");
        }
    }
}

Rolo/Views/Playground/Create.cshtml
@model Rolo.ViewModels.PlaygroundViewModel

@{
    Layout = Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "Playground", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Playground</h4>
        <hr />
       @Html.ValidationSummary(true)
       
        <div class="form-group">
            @Html.Label("Playground Photo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
         
        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude)
                @Html.ValidationMessageFor(model => model.Latitude)
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude)
                @Html.ValidationMessageFor(model => model.Longitude)
            </div>
        </div>
 
        <div class="form-group">
            <p>Playground Features:</p>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Features.InfantSwings)
                <p>Infant swings</p>
                @Html.EditorFor(model => model.Features.Swings)
                <p>Swings</p>
                @Html.EditorFor(model => model.Features.Sandbox)
                <p>Sandbox</p>
                @Html.EditorFor(model => model.Features.InfantSlide)
                <p>Infant slide</p>
                @Html.EditorFor(model => model.Features.Slide)
                <p>Slide</p>
                @Html.EditorFor(model => model.Features.InfantJungleGym)
                <p>Infant jungle gym</p>
            </div>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Features.JungleGym)
                <p>Jungle gym</p>
                @Html.EditorFor(model => model.Features.SeeSaw)
                <p>Seesaw</p>
                @Html.EditorFor(model => model.Features.RockingHorse)
                <p>Spring rider</p>
                @Html.EditorFor(model => model.Features.BalancingEquipment)
                <p>Balancing eqipment</p>
                @Html.EditorFor(model => model.Features.Goal)
                <p>Goal</p>
                @Html.EditorFor(model => model.Features.Basket)
                <p>Basket</p>
                @Html.EditorFor(model => model.Features.PlayHouse)
                <p>Playhouse</p>
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
<div>
    @Html.ActionLink("Back to List", "Index")
</div>


Rolo/Views/Playground/Delete.cshtml
@model Rolo.Models.Playground

@{
    Layout = Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Playground</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rolo/Views/Playground/Details.cshtml
@model Rolo.Models.Playground

@{
    Layout = Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>Playground</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rolo/Views/Playground/Edit.cshtml
@model Rolo.Models.Playground

@{
    Layout = Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Playground</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
    
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude)
                @Html.ValidationMessageFor(model => model.Latitude)
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude)
                @Html.ValidationMessageFor(model => model.Longitude)
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Rolo/Views/Playground/Index.cshtml
@model IEnumerable<Rolo.Models.Playground>

@{
    Layout = Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    </table>